# Generated by Django 4.1.1 on 2022-09-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersDetails',
        ),
    ]
