# Generated by Django 4.1.1 on 2022-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_users_usersdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='pass1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='pass2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
