# Generated by Django 4.1.1 on 2022-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usersdetails_email_usersdetails_pass1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
