# Generated by Django 4.1.1 on 2022-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usersdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='opt1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='opt2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='opt3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='opt4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='question',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
