# Generated by Django 4.1.1 on 2022-09-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usersdetails_opt1_usersdetails_opt2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True)),
                ('question', models.CharField(max_length=30, null=True)),
                ('opt1', models.CharField(max_length=30, null=True)),
                ('opt2', models.CharField(max_length=30, null=True)),
                ('opt3', models.CharField(max_length=30, null=True)),
                ('opt4', models.CharField(max_length=30, null=True)),
                ('created_on_date', models.DateField(auto_now_add=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='opt3',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='opt4',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='question',
        ),
    ]
